### PR TITLE
Ft/Encrypt Password

### PR DESCRIPTION
**Pull request by TuyizeeAnastase**
**What does this PR do?**
To implement password encryption and client validations

**Description of Task to be completed?**
 *  save encrypted client password
 *  Check if the client already exists before creating
 * check client fetched successfully
 
**New Package**
* [bcypt](https://www.npmjs.com/package/bcrypt)

### CODE REVIEW

**Review by Dr-Drake — CHANGES_REQUESTED** [review]
Nice work encrypting the password before saving it.

We also need to be able to "authenticate" (that is get a client), by email and password.
So for the clientExists query, I will be sendinhg password also, so you can compare the email, and password (using bcrypt) to know if the client exists.

**Comment by TuyizeeAnastase** [comment]
> Nice work encrypting the password before saving it.
> 
> We also need to be able to "authenticate" (that is get a client), by email and password. So for the clientExists query, I will be sendinhg password also, so you can compare the email, and password (using bcrypt) to know if the client exists.

**Comment by TuyizeeAnastase** [comment]
> Nice work encrypting the password before saving it.
> 
> We also need to be able to "authenticate" (that is get a client), by email and password. So for the clientExists query, I will be sendinhg password also, so you can compare the email, and password (using bcrypt) to know if the client exists.

**Review by Dr-Drake — APPROVED** [review]
Looks good

**Pull request merged**
